"""Fleet-level analytics endpoints backed by OTEL telemetry data."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Annotated, Any

import structlog
from dishka.integrations.fastapi import DishkaRoute, FromDishka
from fastapi import APIRouter, HTTPException, Query
from sqlalchemy.ext.asyncio import AsyncSession

from backend.models.api_schemas import (
    AnalyticsJobsResponse,
    AnalyticsModelsResponse,
    AnalyticsOverviewResponse,
    AnalyticsPricingResponse,
    AnalyticsReposResponse,
    AnalyticsToolsResponse,
    CostDriversJobResponse,
    CostTrendEntry,
    DismissResponse,
    EditEfficiencyCategory,
    EditEfficiencyResponse,
    FileAccessJobResponse,
    FleetCostDriversResponse,
    FleetFileAccessResponse,
    JobContextResponse,
    ModelComparisonResponse,
    ModelPricingEntry,
    ObservationsListResponse,
    RetryCostResponse,
    ScorecardResponse,
    ShellCommandsResponse,
    TriggerAnalysisResponse,
    TurnEconomicsResponse,
)
from backend.services.analytics_service import AnalyticsService

router = APIRouter(route_class=DishkaRoute, tags=["analytics"])
log = structlog.get_logger()

# ---------------------------------------------------------------------------
# Model pricing — loaded once from the bundled JSON generated by
# tools/update_model_pricing.py (sourced from LiteLLM community data).
# ---------------------------------------------------------------------------

_PRICING_PATH = Path(__file__).resolve().parent.parent / "data" / "model_pricing.json"
_MODEL_PRICING: dict[str, dict[str, object]] | None = None


def _get_model_pricing() -> dict[str, dict[str, object]]:
    global _MODEL_PRICING  # noqa: PLW0603
    if _MODEL_PRICING is None:
        try:
            _MODEL_PRICING = json.loads(_PRICING_PATH.read_text())
            log.info("model_pricing_loaded", count=len(_MODEL_PRICING))
        except FileNotFoundError:
            log.warning("model_pricing_file_missing", path=str(_PRICING_PATH))
            _MODEL_PRICING = {}
        except (json.JSONDecodeError, ValueError, OSError):
            log.exception("model_pricing_load_error")
            _MODEL_PRICING = {}
    return _MODEL_PRICING


def _normalize_model_key(model: str) -> str:
    """Lowercase, collapse non-alnum to hyphens — matches LiteLLM keys."""
    import re

    return re.sub(r"-+", "-", re.sub(r"[^a-z0-9]", "-", model.lower())).strip("-")


@router.get("/analytics/overview", response_model=AnalyticsOverviewResponse)
async def analytics_overview(
    svc: FromDishka[AnalyticsService],
    period: Annotated[int, Query(ge=1, le=365)] = 7,
) -> AnalyticsOverviewResponse:
    """Aggregate analytics over the given period (days)."""
    agg = await svc.aggregate(period_days=period)
    cost_trend = await svc.cost_by_day(period_days=period)

    total_input = agg.get("total_input_tokens", 0)
    total_cache = agg.get("total_cache_read", 0)
    cache_rate = (total_cache / total_input * 100) if total_input else 0

    total_tools = agg.get("total_tool_calls", 0)
    total_failures = agg.get("total_tool_failures", 0)
    total_agent_errors = agg.get("total_agent_errors", 0)
    total_tool_errors = total_failures - total_agent_errors
    tool_success_rate = ((total_tools - total_failures) / total_tools * 100) if total_tools else 100

    return AnalyticsOverviewResponse(
        period=period,
        total_jobs=agg.get("total_jobs", 0),
        succeeded=agg.get("succeeded", 0),
        review=agg.get("review", 0),
        completed=agg.get("completed", 0),
        failed=agg.get("failed", 0),
        cancelled=agg.get("cancelled", 0),
        running=agg.get("running", 0),
        total_cost_usd=float(agg.get("total_cost_usd", 0)),
        total_tokens=agg.get("total_tokens", 0),
        avg_duration_ms=float(agg.get("avg_duration_ms", 0)),
        total_premium_requests=float(agg.get("total_premium_requests", 0)),
        total_tool_calls=total_tools,
        total_tool_failures=total_failures,
        total_agent_errors=total_agent_errors,
        total_tool_errors=max(0, total_tool_errors),
        tool_success_rate=round(tool_success_rate, 1),
        cache_hit_rate=round(cache_rate, 1),
        cost_trend=cost_trend,
        total_subagent_cost_usd=float(agg.get("total_subagent_cost_usd", 0)),
        total_retry_cost_usd=float(agg.get("total_retry_cost_usd", 0)),
        total_retry_count=int(agg.get("total_retry_count", 0)),
    )


@router.get("/analytics/models", response_model=AnalyticsModelsResponse)
async def analytics_models(
    svc: FromDishka[AnalyticsService],
    period: Annotated[int, Query(ge=1, le=365)] = 7,
) -> AnalyticsModelsResponse:
    """Per-model cost and usage breakdown."""
    rows = await svc.cost_by_model(period_days=period)
    return AnalyticsModelsResponse(period=period, models=rows)


@router.get("/analytics/tools", response_model=AnalyticsToolsResponse)
async def analytics_tools(
    svc: FromDishka[AnalyticsService],
    period: Annotated[int, Query(ge=1, le=365)] = 30,
) -> AnalyticsToolsResponse:
    """Tool performance stats (call counts, failure rates, latency)."""
    stats = await svc.tool_stats(period_days=period)
    return AnalyticsToolsResponse(period=period, tools=stats)


@router.get("/analytics/repos", response_model=AnalyticsReposResponse)
async def analytics_repos(
    svc: FromDishka[AnalyticsService],
    period: Annotated[int, Query(ge=1, le=365)] = 7,
) -> AnalyticsReposResponse:
    """Per-repo cost and usage breakdown."""
    rows = await svc.cost_by_repo(period_days=period)
    return AnalyticsReposResponse(period=period, repos=rows)


@router.get("/analytics/jobs", response_model=AnalyticsJobsResponse)
async def analytics_jobs(
    svc: FromDishka[AnalyticsService],
    period: Annotated[int, Query(ge=1, le=365)] = 7,
    sdk: str | None = None,
    model: str | None = None,
    status: str | None = None,
    repo: str | None = None,
    sort: str = "completed_at",
    desc: bool = True,
    limit: Annotated[int, Query(ge=1, le=500)] = 50,
    offset: Annotated[int, Query(ge=0)] = 0,
) -> AnalyticsJobsResponse:
    """Paginated per-job telemetry table."""
    rows = await svc.query_jobs(
        period_days=period,
        sdk=sdk,
        model=model,
        status=status,
        repo=repo,
        sort=sort,
        desc=desc,
        limit=limit,
        offset=offset,
    )
    return AnalyticsJobsResponse(period=period, jobs=rows)


@router.get("/analytics/pricing", response_model=AnalyticsPricingResponse)
def analytics_pricing(
    models: str = Query(
        ...,
        description="Comma-separated model names to look up (e.g. 'claude-sonnet-4-6,claude-opus-4-5')",
    ),
) -> AnalyticsPricingResponse:
    """Return pricing info for the requested models.

    Looks up each model by exact key first, then falls back to normalised
    matching.  Returns ``null`` for models not found in the pricing data.
    """
    result: dict[str, ModelPricingEntry | None] = {}
    for raw in models.split(","):
        name = raw.strip()
        if not name:
            continue
        # Exact match first, then normalised
        entry = _get_model_pricing().get(name)
        if entry is None:
            norm = _normalize_model_key(name)
            entry = _get_model_pricing().get(norm)
        result[name] = ModelPricingEntry(**entry) if entry is not None else None
    return AnalyticsPricingResponse(models=result)


# ---------------------------------------------------------------------------
# Cost Analytics Endpoints
# ---------------------------------------------------------------------------


@router.get("/analytics/cost-drivers/{job_id}", response_model=CostDriversJobResponse)
async def cost_drivers_for_job(
    job_id: str,
    svc: FromDishka[AnalyticsService],
) -> CostDriversJobResponse:
    """Per-job cost attribution breakdown by dimension."""
    rows = await svc.cost_drivers_for_job(job_id)
    by_dimension: dict[str, list[dict[str, Any]]] = {}
    for row in rows:
        dim = row.get("dimension", "unknown")
        by_dimension.setdefault(dim, []).append(dict(row))
    return CostDriversJobResponse(job_id=job_id, dimensions=by_dimension)


@router.get("/analytics/cost-drivers", response_model=FleetCostDriversResponse)
async def fleet_cost_drivers(
    svc: FromDishka[AnalyticsService],
    period: Annotated[int, Query(ge=1, le=365)] = 30,
    dimension: str | None = None,
) -> FleetCostDriversResponse:
    """Fleet-wide cost attribution: top cost buckets across all dimensions."""
    if dimension:
        rows = await svc.cost_by_dimension(dimension, period_days=period)
        return FleetCostDriversResponse(period=period, dimension=dimension, buckets=rows)
    summary = await svc.fleet_cost_summary(period_days=period)
    # Activity-dimension costs use an equal-weight heuristic per turn, flag them.
    enriched: list[dict[str, Any]] = [dict(r) for r in summary]
    for row in enriched:
        row["confidence"] = "approximate" if row.get("dimension") == "activity" else "exact"
    return FleetCostDriversResponse(period=period, summary=enriched)


@router.get("/analytics/file-access/{job_id}", response_model=FileAccessJobResponse)
async def file_access_for_job(
    job_id: str,
    svc: FromDishka[AnalyticsService],
) -> FileAccessJobResponse:
    """File access stats for a job — rereads, most-accessed files."""
    stats = await svc.reread_stats(job_id)
    top_files = await svc.most_accessed_files(job_id=job_id)
    return FileAccessJobResponse(job_id=job_id, stats=stats, top_files=top_files)


@router.get("/analytics/file-access", response_model=FleetFileAccessResponse)
async def fleet_file_access(
    svc: FromDishka[AnalyticsService],
    period: Annotated[int, Query(ge=1, le=365)] = 30,
) -> FleetFileAccessResponse:
    """Fleet-wide most-accessed files across all jobs."""
    top_files = await svc.most_accessed_files(period_days=period)
    return FleetFileAccessResponse(period=period, top_files=top_files)


@router.get("/analytics/turn-economics/{job_id}", response_model=TurnEconomicsResponse)
async def turn_economics_for_job(
    job_id: str,
    svc: FromDishka[AnalyticsService],
) -> TurnEconomicsResponse:
    """Per-turn cost curve for a specific job."""
    summary = await svc.get_summary(job_id)
    turns = await svc.cost_drivers_for_job(job_id)
    turn_data = [r for r in turns if r.get("dimension") == "turn"]
    return TurnEconomicsResponse(
        job_id=job_id,
        total_turns=summary.get("total_turns", 0) if summary else 0,
        peak_turn_cost_usd=summary.get("peak_turn_cost_usd", 0) if summary else 0,
        avg_turn_cost_usd=summary.get("avg_turn_cost_usd", 0) if summary else 0,
        cost_first_half_usd=summary.get("cost_first_half_usd", 0) if summary else 0,
        cost_second_half_usd=summary.get("cost_second_half_usd", 0) if summary else 0,
        turn_curve=turn_data,
    )


# ---------------------------------------------------------------------------
# Scorecard / Redesigned Analytics
# ---------------------------------------------------------------------------


@router.get("/analytics/scorecard", response_model=ScorecardResponse)
async def analytics_scorecard(
    svc: FromDishka[AnalyticsService],
    period: Annotated[int, Query(ge=1, le=365)] = 7,
) -> ScorecardResponse:
    """Top-level scorecard: budget per SDK, activity with resolution, quota, cost trend."""
    from backend.config import load_config

    scorecard = await svc.scorecard(period_days=period)
    cfg = load_config()
    scorecard["dailySpendLimitUsd"] = cfg.telemetry.daily_spend_limit_usd
    return ScorecardResponse(**scorecard)


@router.get("/analytics/model-comparison", response_model=ModelComparisonResponse)
async def analytics_model_comparison(
    svc: FromDishka[AnalyticsService],
    period: Annotated[int, Query(ge=1, le=365)] = 30,
    repo: str | None = None,
) -> ModelComparisonResponse:
    """Per-model comparison with resolution data joined from jobs table."""
    rows = await svc.model_comparison(period_days=period, repo=repo)
    return ModelComparisonResponse(period=period, repo=repo, models=rows)


@router.get("/analytics/job-context/{job_id}", response_model=JobContextResponse)
async def analytics_job_context(
    job_id: str,
    svc: FromDishka[AnalyticsService],
) -> JobContextResponse:
    """Per-job context: metrics + repo comparison + noteworthy flags."""
    job_context = await svc.job_context(job_id)
    if job_context is None:
        raise HTTPException(status_code=404, detail="Job telemetry not found")
    return JobContextResponse(**job_context)


# ---------------------------------------------------------------------------
# Statistical Observations
# ---------------------------------------------------------------------------


@router.get("/analytics/observations", response_model=ObservationsListResponse)
async def list_observations(
    svc: FromDishka[AnalyticsService],
    category: str | None = None,
    severity: str | None = None,
) -> ObservationsListResponse:
    """List active cost observations / anomalies."""
    rows = await svc.list_observations(category=category, severity=severity)
    return ObservationsListResponse(observations=rows)


@router.post("/analytics/observations/{observation_id}/dismiss", response_model=DismissResponse)
async def dismiss_observation(
    observation_id: int,
    svc: FromDishka[AnalyticsService],
) -> DismissResponse:
    """Dismiss an observation."""
    await svc.dismiss_observation(observation_id)
    return DismissResponse(status="dismissed")


@router.post("/analytics/analyse", response_model=TriggerAnalysisResponse)
async def trigger_analysis(
    session: FromDishka[AsyncSession],
) -> TriggerAnalysisResponse:
    """Manually trigger the statistical analysis pass."""
    from backend.services.statistical_analysis import run_analysis

    count = await run_analysis(session)
    await session.commit()
    return TriggerAnalysisResponse(observations_written=count)


# ---------------------------------------------------------------------------
# Shell command breakdown
# ---------------------------------------------------------------------------


@router.get("/analytics/shell-commands", response_model=ShellCommandsResponse)
async def shell_command_breakdown(
    svc: FromDishka[AnalyticsService],
    period: Annotated[int, Query(ge=1, le=365)] = 30,
) -> ShellCommandsResponse:
    """Top shell commands by call count, aggregated from tool_target."""
    rows = await svc.shell_command_breakdown(period_days=period)
    return ShellCommandsResponse(period=period, commands=rows)


# ---------------------------------------------------------------------------
# Retry cost summary
# ---------------------------------------------------------------------------


@router.get("/analytics/retry-cost", response_model=RetryCostResponse)
async def retry_cost_summary(
    svc: FromDishka[AnalyticsService],
    period: Annotated[int, Query(ge=1, le=365)] = 30,
) -> RetryCostResponse:
    """Fleet-wide retry cost and count."""
    summary = await svc.retry_cost_summary(period_days=period)
    total = float(summary.get("total_cost_usd") or 0)
    retry = float(summary.get("retry_cost_usd") or 0)
    return RetryCostResponse(
        period=period,
        retry_cost_usd=retry,
        retry_count=summary.get("retry_count", 0),
        total_spans=summary.get("total_spans", 0),
        total_cost_usd=total,
        retry_pct=round((retry / total * 100) if total > 0 else 0, 1),
    )


# ---------------------------------------------------------------------------
# Edit efficiency / one-shot rate
# ---------------------------------------------------------------------------


@router.get("/analytics/edit-efficiency", response_model=EditEfficiencyResponse)
async def fleet_edit_efficiency(
    svc: FromDishka[AnalyticsService],
    period: Annotated[int, Query(ge=1, le=365)] = 30,
) -> EditEfficiencyResponse:
    """Fleet-wide one-shot success rate by activity category.

    Reads the ``edit_efficiency`` dimension from cost attribution rows.
    ``call_count`` = edit turns, ``input_tokens`` = one-shot turns,
    ``output_tokens`` = total retries (repurposed columns).
    """
    rows = await svc.cost_by_dimension("edit_efficiency", period_days=period)
    categories = []
    for row in rows:
        edit_turns = int(row.get("call_count") or 0)
        one_shot = int(row.get("input_tokens") or 0)
        retries = int(row.get("output_tokens") or 0)
        rate = round((one_shot / edit_turns * 100) if edit_turns > 0 else 0, 1)
        categories.append(EditEfficiencyCategory(
            activity=row.get("bucket", ""),
            edit_turns=edit_turns,
            one_shot_turns=one_shot,
            retries=retries,
            one_shot_rate=rate,
            job_count=row.get("job_count", 0),
        ))
    return EditEfficiencyResponse(period=period, categories=categories)
