/**
 * Mock API response fixtures for Playwright capture.
 *
 * All data mirrors the exact shapes from backend/models/api_schemas.py
 * and matches the scenario described in SCREENSHOTS_NEEDED.md:
 * 10+ jobs across 2 repos, mixed agents, mixed states.
 */

const BASE_TIME = new Date("2026-03-31T14:30:00Z");
function minutesAgo(n: number) {
  return new Date(BASE_TIME.getTime() - n * 60_000).toISOString();
}

// ---------------------------------------------------------------------------
// Jobs (non-archived, visible on dashboard)
// ---------------------------------------------------------------------------

const JOB_DEFAULTS = {
  baseRef: "main",
  worktreePath: null,
  permissionMode: "full_auto",
  prUrl: null,
  mergeStatus: null,
  resolution: null,
  archivedAt: null,
  failureReason: null,
  progressHeadline: null,
  progressSummary: null,
  worktreeName: null,
  verify: null,
  selfReview: null,
  maxTurns: null,
  verifyPrompt: null,
  selfReviewPrompt: null,
  parentJobId: null,
  modelDowngraded: false,
  requestedModel: null,
  actualModel: null,
  completedAt: null,
  conflictFiles: null,
  resolutionError: null,
};

export const REPO_ISSUE_TRACKER = "/home/dev/repos/demo-issue-tracker-api";
export const REPO_SUPPORT_DASH = "/home/dev/repos/demo-support-dashboard";

export const mockJobs = [
  // ── In Progress column ──────────────────────────────────────────────
  {
    ...JOB_DEFAULTS,
    id: "loading-skeleton-ticket-list",
    state: "running",
    title: "Persist the selected status filter in the URL query string",
    prompt: "Persist the selected status filter in the URL query string so the view survives page refreshes",
    repo: REPO_SUPPORT_DASH,
    sdk: "copilot",
    branch: "feat/loading-skeleton-ticket-list",
    model: "claude-sonnet-4.6",
    progressHeadline: "Writing filter serialization logic",
    progressSummary: "Serializing active filters to URL search params",
    createdAt: minutesAgo(25),
    updatedAt: minutesAgo(1),
  },
  {
    ...JOB_DEFAULTS,
    id: "customer-email-search",
    state: "running",
    title: "Add customer email search to the ticket list endpoint",
    prompt: "Add customer email search to the ticket list endpoint and add tests",
    repo: REPO_ISSUE_TRACKER,
    sdk: "copilot",
    branch: "feat/customer-email-search-tickets",
    model: "claude-sonnet-4.6",
    progressHeadline: "Writing test cases",
    progressSummary: "Adding unit tests for email search filter",
    createdAt: minutesAgo(18),
    updatedAt: minutesAgo(2),
  },
  {
    ...JOB_DEFAULTS,
    id: "409-conflict-archive-ticket",
    state: "queued",
    title: "Return 409 Conflict when archiving an already-archived ticket",
    prompt: "Return 409 Conflict when archiving an already-archived ticket and add a test",
    repo: REPO_ISSUE_TRACKER,
    sdk: "copilot",
    branch: null,
    model: "claude-sonnet-4.6",
    createdAt: minutesAgo(3),
    updatedAt: minutesAgo(3),
  },
  {
    ...JOB_DEFAULTS,
    id: "persist-status-filter-url",
    state: "queued",
    title: "Add a loading skeleton to the ticket list",
    prompt: "Add a loading skeleton to the ticket list while the API request is in flight",
    repo: REPO_SUPPORT_DASH,
    sdk: "copilot",
    branch: null,
    model: "claude-sonnet-4.6",
    createdAt: minutesAgo(2),
    updatedAt: minutesAgo(2),
  },

  // ── Awaiting Input column ───────────────────────────────────────────
  {
    ...JOB_DEFAULTS,
    id: "ticket-list-pagination",
    state: "review",
    title: "Add pagination to the ticket list endpoint",
    prompt: "Add pagination to the ticket list endpoint with limit and offset query params",
    repo: REPO_ISSUE_TRACKER,
    sdk: "copilot",
    branch: "feat/ticket-list-pagination",
    model: "claude-sonnet-4.6",
    resolution: "unresolved",
    createdAt: minutesAgo(90),
    updatedAt: minutesAgo(58),
    completedAt: minutesAgo(60),
  },
  {
    ...JOB_DEFAULTS,
    id: "ticket-archival-error-codes",
    state: "review",
    title: "Tighten error handling around ticket archival",
    prompt: "Tighten error handling around ticket archival — return proper 404/409 codes",
    repo: REPO_ISSUE_TRACKER,
    sdk: "claude",
    branch: "fix/ticket-archival-error-codes",
    model: "claude-sonnet-4.6",
    resolution: "unresolved",
    createdAt: minutesAgo(75),
    updatedAt: minutesAgo(53),
    completedAt: minutesAgo(55),
  },
  {
    ...JOB_DEFAULTS,
    id: "keyboard-shortcut-hints",
    state: "waiting_for_approval",
    title: "Add keyboard shortcut hints to the search input and status filter",
    prompt: "Add keyboard shortcut hints to the search input and status filter",
    repo: REPO_SUPPORT_DASH,
    sdk: "claude",
    branch: "feat/keyboard-shortcut-hints",
    model: "claude-sonnet-4.6",
    permissionMode: "review_and_approve",
    progressHeadline: "Waiting for approval",
    createdAt: minutesAgo(12),
    updatedAt: minutesAgo(5),
  },
  {
    ...JOB_DEFAULTS,
    id: "priority-badge-column",
    state: "completed",
    title: "Add a priority badge column to the ticket table",
    prompt: "Add a priority badge column to the ticket table with color-coded labels",
    repo: REPO_SUPPORT_DASH,
    sdk: "claude",
    branch: "feat/priority-badge-column",
    model: "claude-sonnet-4.6",
    resolution: "merged",
    prUrl: "https://github.com/acme/demo-support-dashboard/pull/14",
    createdAt: minutesAgo(120),
    updatedAt: minutesAgo(98),
    completedAt: minutesAgo(100),
  },

  // ── Failed column ──────────────────────────────────────────────────
  {
    ...JOB_DEFAULTS,
    id: "migrate-test-vitest",
    state: "failed",
    title: "Migrate test suite to Vitest",
    prompt: "Migrate the existing Jest test suite to Vitest",
    repo: REPO_SUPPORT_DASH,
    sdk: "copilot",
    branch: "chore/migrate-test-vitest",
    model: "claude-sonnet-4.6",
    failureReason: "Test runner configuration incompatible with existing jest.config.ts — multiple transform conflicts",
    createdAt: minutesAgo(40),
    updatedAt: minutesAgo(32),
  },
];

// ---------------------------------------------------------------------------
// Job detail: running job j-0007 (transcript, timeline, artifacts)
// ---------------------------------------------------------------------------

const TURN_A = "turn-001";
const TURN_B = "turn-002";
const TURN_C = "turn-003";

export const runningJobTranscript = [
  // Turn 1: Initial analysis
  {
    jobId: "customer-email-search",
    seq: 1,
    timestamp: minutesAgo(17),
    role: "reasoning",
    content: "I need to understand the existing ticket list endpoint and its query parameters before adding email search. Let me start by reading the route handler.",
    turnId: TURN_A,
  },
  {
    jobId: "customer-email-search",
    seq: 2,
    timestamp: minutesAgo(17),
    role: "tool_call",
    content: "",
    turnId: TURN_A,
    toolName: "read_file",
    toolArgs: '{"path": "src/routes/tickets.py", "startLine": 1, "endLine": 80}',
    toolResult: "from fastapi import APIRouter, Query, Depends\nfrom ..models import Ticket, TicketFilter\nfrom ..services.ticket_service import TicketService\n\nrouter = APIRouter(prefix=\"/tickets\", tags=[\"tickets\"])\n\n@router.get(\"/\")\nasync def list_tickets(\n    status: str | None = Query(None),\n    priority: str | None = Query(None),\n    limit: int = Query(20, ge=1, le=100),\n    offset: int = Query(0, ge=0),\n    svc: TicketService = Depends(),\n) -> list[Ticket]:\n    return await svc.list_tickets(status=status, priority=priority, limit=limit, offset=offset)",
    toolSuccess: true,
    toolDisplay: "Read src/routes/tickets.py L1-80",
    toolDisplayFull: "Read src/routes/tickets.py L1-80",
    toolDurationMs: 45,
  },
  {
    jobId: "customer-email-search",
    seq: 3,
    timestamp: minutesAgo(17),
    role: "tool_call",
    content: "",
    turnId: TURN_A,
    toolName: "read_file",
    toolArgs: '{"path": "src/services/ticket_service.py", "startLine": 1, "endLine": 60}',
    toolResult: "from sqlalchemy import select, func\nfrom ..models import Ticket\n\nclass TicketService:\n    def __init__(self, db):\n        self.db = db\n\n    async def list_tickets(self, *, status=None, priority=None, limit=20, offset=0):\n        q = select(Ticket)\n        if status:\n            q = q.where(Ticket.status == status)\n        if priority:\n            q = q.where(Ticket.priority == priority)\n        q = q.offset(offset).limit(limit)\n        result = await self.db.execute(q)\n        return result.scalars().all()",
    toolSuccess: true,
    toolDisplay: "Read src/services/ticket_service.py L1-60",
    toolDisplayFull: "Read src/services/ticket_service.py L1-60",
    toolDurationMs: 38,
  },
  {
    jobId: "customer-email-search",
    seq: 4,
    timestamp: minutesAgo(16),
    role: "tool_call",
    content: "",
    turnId: TURN_A,
    toolName: "grep_search",
    toolArgs: '{"query": "customer_email|email", "includePattern": "src/**/*.py"}',
    toolResult: "src/models/ticket.py:12:    customer_email: str = Field(...)\nsrc/models/ticket.py:24:    email: str | None = None  # filter alias",
    toolSuccess: true,
    toolDisplay: 'Search "customer_email|email" in src/**/*.py',
    toolDisplayFull: 'Search "customer_email|email" in src/**/*.py',
    toolDurationMs: 120,
  },
  {
    jobId: "customer-email-search",
    seq: 5,
    timestamp: minutesAgo(16),
    role: "agent",
    content: "I've analyzed the existing codebase. The ticket list endpoint in `src/routes/tickets.py` already supports `status` and `priority` filters. The `Ticket` model has a `customer_email` field. I need to:\n\n1. Add an `email` query parameter to the route handler\n2. Update `TicketService.list_tickets()` to filter by email\n3. Write tests for the new filter",
    turnId: TURN_A,
    title: "Analysis complete",
  },

  // Turn 2: Implementation
  {
    jobId: "customer-email-search",
    seq: 6,
    timestamp: minutesAgo(14),
    role: "reasoning",
    content: "Now I'll add the email search parameter. I should use `ilike` for case-insensitive partial matching so users can search by partial email addresses.",
    turnId: TURN_B,
  },
  {
    jobId: "customer-email-search",
    seq: 7,
    timestamp: minutesAgo(14),
    role: "tool_call",
    content: "",
    turnId: TURN_B,
    toolName: "replace_string_in_file",
    toolArgs: '{"filePath": "src/routes/tickets.py", "oldString": "    offset: int = Query(0, ge=0),", "newString": "    offset: int = Query(0, ge=0),\\n    email: str | None = Query(None, description=\\"Filter by customer email (partial match)\\"),"}',
    toolResult: "Successfully replaced string in src/routes/tickets.py",
    toolSuccess: true,
    toolDisplay: "Edit src/routes/tickets.py",
    toolDisplayFull: "Edit src/routes/tickets.py",
    toolDurationMs: 52,
  },
  {
    jobId: "customer-email-search",
    seq: 8,
    timestamp: minutesAgo(13),
    role: "tool_call",
    content: "",
    turnId: TURN_B,
    toolName: "replace_string_in_file",
    toolArgs: '{"filePath": "src/routes/tickets.py", "oldString": "    return await svc.list_tickets(status=status, priority=priority, limit=limit, offset=offset)", "newString": "    return await svc.list_tickets(status=status, priority=priority, email=email, limit=limit, offset=offset)"}',
    toolResult: "Successfully replaced string in src/routes/tickets.py",
    toolSuccess: true,
    toolDisplay: "Edit src/routes/tickets.py",
    toolDisplayFull: "Edit src/routes/tickets.py",
    toolDurationMs: 48,
  },
  {
    jobId: "customer-email-search",
    seq: 9,
    timestamp: minutesAgo(12),
    role: "tool_call",
    content: "",
    turnId: TURN_B,
    toolName: "replace_string_in_file",
    toolArgs: '{"filePath": "src/services/ticket_service.py"}',
    toolResult: "Successfully replaced string in src/services/ticket_service.py",
    toolSuccess: true,
    toolDisplay: "Edit src/services/ticket_service.py",
    toolDisplayFull: "Edit src/services/ticket_service.py",
    toolDurationMs: 55,
  },
  {
    jobId: "customer-email-search",
    seq: 10,
    timestamp: minutesAgo(11),
    role: "tool_call",
    content: "",
    turnId: TURN_B,
    toolName: "run_in_terminal",
    toolArgs: '{"command": "cd /home/dev/repos/demo-issue-tracker-api && python -m pytest tests/ -x --tb=short"}',
    toolResult: "======================== test session starts =========================\ncollected 14 items\ntests/test_tickets.py::test_list_tickets PASSED\ntests/test_tickets.py::test_filter_by_status PASSED\ntests/test_tickets.py::test_filter_by_priority PASSED\ntests/test_tickets.py::test_pagination PASSED\ntests/test_archival.py::test_archive_ticket PASSED\ntests/test_archival.py::test_archive_already_archived PASSED\n========================= 14 passed in 2.34s =========================",
    toolSuccess: true,
    toolDisplay: "$ python -m pytest tests/ -x --tb=short",
    toolDisplayFull: "$ python -m pytest tests/ -x --tb=short",
    toolDurationMs: 3420,
  },
  {
    jobId: "customer-email-search",
    seq: 11,
    timestamp: minutesAgo(10),
    role: "agent",
    content: "I've added the `email` query parameter to the ticket list endpoint with case-insensitive partial matching using `ilike`. All existing tests pass. Now I'll write tests specifically for the email search functionality.",
    turnId: TURN_B,
    title: "Email filter implemented",
  },

  // Turn 3: Writing tests (in progress)
  {
    jobId: "customer-email-search",
    seq: 12,
    timestamp: minutesAgo(8),
    role: "reasoning",
    content: "I should write comprehensive tests covering: exact match, partial match, case insensitivity, no results, and combination with other filters.",
    turnId: TURN_C,
  },
  {
    jobId: "customer-email-search",
    seq: 13,
    timestamp: minutesAgo(7),
    role: "tool_call",
    content: "",
    turnId: TURN_C,
    toolName: "create_file",
    toolArgs: '{"filePath": "tests/test_email_search.py"}',
    toolResult: "File created: tests/test_email_search.py",
    toolSuccess: true,
    toolDisplay: "Create tests/test_email_search.py",
    toolDisplayFull: "Create tests/test_email_search.py",
    toolDurationMs: 32,
  },
  {
    jobId: "customer-email-search",
    seq: 14,
    timestamp: minutesAgo(5),
    role: "tool_call",
    content: "",
    turnId: TURN_C,
    toolName: "run_in_terminal",
    toolArgs: '{"command": "cd /home/dev/repos/demo-issue-tracker-api && python -m pytest tests/test_email_search.py -v"}',
    toolResult: "======================== test session starts =========================\ncollected 5 items\ntests/test_email_search.py::test_search_by_exact_email PASSED\ntests/test_email_search.py::test_search_by_partial_email PASSED\ntests/test_email_search.py::test_search_case_insensitive PASSED\ntests/test_email_search.py::test_search_no_results PASSED\ntests/test_email_search.py::test_search_combined_with_status PASSED\n========================= 5 passed in 1.87s =========================",
    toolSuccess: true,
    toolDisplay: "$ python -m pytest tests/test_email_search.py -v",
    toolDisplayFull: "$ python -m pytest tests/test_email_search.py -v",
    toolDurationMs: 2870,
  },
  {
    jobId: "customer-email-search",
    seq: 15,
    timestamp: minutesAgo(3),
    role: "tool_running",
    content: "",
    turnId: TURN_C,
    toolName: "run_in_terminal",
    toolDisplay: "$ python -m pytest tests/ -v --tb=short",
    toolDisplayFull: "$ python -m pytest tests/ -v --tb=short",
  },
];

export const runningJobTimeline = [
  {
    headline: "Cloning repository",
    headlinePast: "Cloned repository",
    summary: "demo-issue-tracker-api -> local workspace",
    timestamp: minutesAgo(18),
    active: false,
  },
  {
    headline: "Creating worktree",
    headlinePast: "Created worktree on feat/customer-email-search-tickets",
    summary: "Isolated branch for safe modification",
    timestamp: minutesAgo(18),
    active: false,
  },
  {
    headline: "Analyzing codebase",
    headlinePast: "Analyzed ticket list endpoint and service layer",
    summary: "Found customer_email field in Ticket model",
    timestamp: minutesAgo(17),
    active: false,
  },
  {
    headline: "Implementing email search filter",
    headlinePast: "Added email search to ticket list endpoint",
    summary: "Case-insensitive partial match with ilike",
    timestamp: minutesAgo(14),
    active: false,
  },
  {
    headline: "Writing test suite",
    headlinePast: "Wrote email search tests",
    summary: "5 test cases covering exact, partial, case-insensitive, no results",
    timestamp: minutesAgo(8),
    active: false,
  },
  {
    headline: "Running full test suite",
    headlinePast: "Full test suite passing",
    summary: "",
    timestamp: minutesAgo(3),
    active: true,
  },
];

export const runningJobPlan = [
  { label: "Read existing ticket list endpoint", status: "done" as const },
  { label: "Add email query parameter to route", status: "done" as const },
  { label: "Update service layer with ilike filter", status: "done" as const },
  { label: "Write email search test cases", status: "done" as const },
  { label: "Run full test suite", status: "active" as const },
];

// Turn summaries that populate the activity timeline sidebar
const ACT_A = "act-001";
const ACT_B = "act-002";
const ACT_C = "act-003";

export const runningJobTurnSummaries = [
  {
    jobId: "customer-email-search",
    turnId: TURN_A,
    title: "Analyzed ticket list endpoint and service layer",
    activityId: ACT_A,
    activityLabel: "Analyzing codebase",
    activityStatus: "done",
    isNewActivity: true,
    planItemId: null,
  },
  {
    jobId: "customer-email-search",
    turnId: TURN_B,
    title: "Added email search filter with ilike matching",
    activityId: ACT_B,
    activityLabel: "Implementing email search",
    activityStatus: "done",
    isNewActivity: true,
    planItemId: null,
  },
  {
    jobId: "customer-email-search",
    turnId: TURN_C,
    title: "Writing and running email search tests",
    activityId: ACT_C,
    activityLabel: "Writing tests",
    activityStatus: "active",
    isNewActivity: true,
    planItemId: null,
  },
];

// ---------------------------------------------------------------------------
// Job detail: approval job j-0008
// ---------------------------------------------------------------------------

export const approvalJobApprovals = [
  {
    id: "apr-001",
    jobId: "keyboard-shortcut-hints",
    description: "Write file: src/components/SearchInput.tsx — Replace the placeholder text with keyboard shortcut hint markup",
    proposedAction: 'replace_string_in_file: src/components/SearchInput.tsx\n- placeholder="Search tickets..."\n+ placeholder="Search tickets..." aria-keyshortcuts="Control+K"\n+ <kbd className="shortcut-hint">⌘K</kbd>',
    requestedAt: minutesAgo(5),
    resolvedAt: null,
    resolution: null,
    requiresExplicitApproval: false,
  },
  {
    id: "apr-002",
    jobId: "keyboard-shortcut-hints",
    description: "Execute command: npm run build — Verify the shortcut hints render correctly after modification",
    proposedAction: "$ npm run build",
    requestedAt: minutesAgo(5),
    resolvedAt: null,
    resolution: null,
    requiresExplicitApproval: false,
  },
];

// ---------------------------------------------------------------------------
// Job detail: review job j-0003 (diff)
// ---------------------------------------------------------------------------

export const reviewJobDiff = [
  {
    path: "src/routes/tickets.py",
    status: "modified",
    additions: 12,
    deletions: 3,
    hunks: [
      {
        oldStart: 8,
        oldLines: 10,
        newStart: 8,
        newLines: 19,
        lines: [
          { type: "context", content: "@router.get(\"/\")" },
          { type: "context", content: "async def list_tickets(" },
          { type: "context", content: "    status: str | None = Query(None)," },
          { type: "context", content: "    priority: str | None = Query(None)," },
          { type: "deletion", content: "    limit: int = Query(20, ge=1, le=100)," },
          { type: "deletion", content: "    offset: int = Query(0, ge=0)," },
          { type: "addition", content: "    limit: int = Query(20, ge=1, le=100, description=\"Max items per page\")," },
          { type: "addition", content: "    offset: int = Query(0, ge=0, description=\"Number of items to skip\")," },
          { type: "context", content: "    svc: TicketService = Depends()," },
          { type: "deletion", content: ") -> list[Ticket]:" },
          { type: "addition", content: ") -> PaginatedResponse[Ticket]:" },
          { type: "addition", content: "    total = await svc.count_tickets(status=status, priority=priority)" },
          { type: "addition", content: "    items = await svc.list_tickets(" },
          { type: "addition", content: "        status=status, priority=priority, limit=limit, offset=offset" },
          { type: "addition", content: "    )" },
          { type: "addition", content: "    return PaginatedResponse(" },
          { type: "addition", content: "        items=items," },
          { type: "addition", content: "        total=total," },
          { type: "addition", content: "        limit=limit," },
          { type: "addition", content: "        offset=offset," },
          { type: "addition", content: "    )" },
        ],
      },
    ],
  },
  {
    path: "src/models/pagination.py",
    status: "added",
    additions: 18,
    deletions: 0,
    hunks: [
      {
        oldStart: 0,
        oldLines: 0,
        newStart: 1,
        newLines: 18,
        lines: [
          { type: "addition", content: "from typing import Generic, TypeVar" },
          { type: "addition", content: "from pydantic import BaseModel, Field" },
          { type: "addition", content: "" },
          { type: "addition", content: "T = TypeVar(\"T\")" },
          { type: "addition", content: "" },
          { type: "addition", content: "class PaginatedResponse(BaseModel, Generic[T]):" },
          { type: "addition", content: "    \"\"\"Paginated list response with total count.\"\"\"" },
          { type: "addition", content: "    items: list[T]" },
          { type: "addition", content: "    total: int = Field(ge=0)" },
          { type: "addition", content: "    limit: int = Field(ge=1)" },
          { type: "addition", content: "    offset: int = Field(ge=0)" },
          { type: "addition", content: "" },
          { type: "addition", content: "    @property" },
          { type: "addition", content: "    def has_more(self) -> bool:" },
          { type: "addition", content: "        return self.offset + self.limit < self.total" },
          { type: "addition", content: "" },
          { type: "addition", content: "    @property" },
          { type: "addition", content: "    def page(self) -> int:" },
          { type: "addition", content: "        return self.offset // self.limit + 1" },
        ],
      },
    ],
  },
  {
    path: "src/services/ticket_service.py",
    status: "modified",
    additions: 8,
    deletions: 0,
    hunks: [
      {
        oldStart: 15,
        oldLines: 4,
        newStart: 15,
        newLines: 12,
        lines: [
          { type: "context", content: "        result = await self.db.execute(q)" },
          { type: "context", content: "        return result.scalars().all()" },
          { type: "context", content: "" },
          { type: "addition", content: "    async def count_tickets(self, *, status=None, priority=None) -> int:" },
          { type: "addition", content: "        q = select(func.count()).select_from(Ticket)" },
          { type: "addition", content: "        if status:" },
          { type: "addition", content: "            q = q.where(Ticket.status == status)" },
          { type: "addition", content: "        if priority:" },
          { type: "addition", content: "            q = q.where(Ticket.priority == priority)" },
          { type: "addition", content: "        result = await self.db.execute(q)" },
          { type: "addition", content: "        return result.scalar_one()" },
          { type: "addition", content: "" },
          { type: "context", content: "    async def archive_ticket(self, ticket_id: str) -> Ticket:" },
        ],
      },
    ],
  },
  {
    path: "tests/test_pagination.py",
    status: "added",
    additions: 42,
    deletions: 0,
    hunks: [
      {
        oldStart: 0,
        oldLines: 0,
        newStart: 1,
        newLines: 42,
        lines: [
          { type: "addition", content: "import pytest" },
          { type: "addition", content: "from httpx import AsyncClient" },
          { type: "addition", content: "" },
          { type: "addition", content: "@pytest.mark.asyncio" },
          { type: "addition", content: "async def test_default_pagination(client: AsyncClient):" },
          { type: "addition", content: "    resp = await client.get(\"/tickets\")" },
          { type: "addition", content: "    assert resp.status_code == 200" },
          { type: "addition", content: "    data = resp.json()" },
          { type: "addition", content: "    assert \"items\" in data" },
          { type: "addition", content: "    assert \"total\" in data" },
          { type: "addition", content: "    assert data[\"limit\"] == 20" },
          { type: "addition", content: "    assert data[\"offset\"] == 0" },
          { type: "addition", content: "" },
          { type: "addition", content: "@pytest.mark.asyncio" },
          { type: "addition", content: "async def test_custom_limit_offset(client: AsyncClient):" },
          { type: "addition", content: "    resp = await client.get(\"/tickets?limit=5&offset=10\")" },
          { type: "addition", content: "    assert resp.status_code == 200" },
          { type: "addition", content: "    data = resp.json()" },
          { type: "addition", content: "    assert data[\"limit\"] == 5" },
          { type: "addition", content: "    assert data[\"offset\"] == 10" },
          { type: "addition", content: "" },
          { type: "addition", content: "@pytest.mark.asyncio" },
          { type: "addition", content: "async def test_total_reflects_filter(client: AsyncClient):" },
          { type: "addition", content: "    resp = await client.get(\"/tickets?status=open\")" },
          { type: "addition", content: "    data = resp.json()" },
          { type: "addition", content: "    all_resp = await client.get(\"/tickets\")" },
          { type: "addition", content: "    all_data = all_resp.json()" },
          { type: "addition", content: "    assert data[\"total\"] <= all_data[\"total\"]" },
          { type: "addition", content: "" },
          { type: "addition", content: "@pytest.mark.asyncio" },
          { type: "addition", content: "async def test_has_more_flag(client: AsyncClient):" },
          { type: "addition", content: "    resp = await client.get(\"/tickets?limit=1\")" },
          { type: "addition", content: "    data = resp.json()" },
          { type: "addition", content: "    # With test fixtures having multiple tickets, has_more should be True" },
          { type: "addition", content: "    if data[\"total\"] > 1:" },
          { type: "addition", content: "        assert data[\"offset\"] + data[\"limit\"] < data[\"total\"]" },
          { type: "addition", content: "" },
          { type: "addition", content: "@pytest.mark.asyncio" },
          { type: "addition", content: "async def test_invalid_limit_rejected(client: AsyncClient):" },
          { type: "addition", content: "    resp = await client.get(\"/tickets?limit=0\")" },
          { type: "addition", content: "    assert resp.status_code == 422" },
          { type: "addition", content: "    resp = await client.get(\"/tickets?limit=200\")" },
          { type: "addition", content: "    assert resp.status_code == 422" },
        ],
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// Health, SDKs, Models, Settings
// ---------------------------------------------------------------------------

export const mockHealth = {
  status: "healthy",
  version: "0.12.0",
  uptimeSeconds: 86400,
  activeJobs: 2,
  queuedJobs: 2,
};

export const mockSdks = {
  default: "copilot",
  sdks: [
    {
      id: "copilot",
      name: "GitHub Copilot",
      enabled: true,
      status: "ready",
      authenticated: true,
      hint: "",
    },
    {
      id: "claude",
      name: "Claude Code",
      enabled: true,
      status: "ready",
      authenticated: true,
      hint: "",
    },
  ],
};

export const mockModels = [
  { id: "claude-sonnet-4.6", name: "Claude Sonnet 4.6", isDefault: true },
  { id: "claude-haiku-4-5", name: "Claude Haiku 4.5", isDefault: false },
  { id: "claude-opus-4.6", name: "Claude Opus 4.6", isDefault: false },
];

export const mockSettings = {
  maxConcurrentJobs: 3,
  permissionMode: "full_auto",
  autoPush: false,
  cleanupWorktree: true,
  deleteBranchAfterMerge: false,
  artifactRetentionDays: 30,
  maxArtifactSizeMb: 50,
  autoArchiveDays: 0,
  verify: false,
  selfReview: false,
  maxTurns: 200,
  verifyPrompt: "",
  selfReviewPrompt: "",
};

export const mockRepoList = {
  items: [REPO_ISSUE_TRACKER, REPO_SUPPORT_DASH],
};

// ---------------------------------------------------------------------------
// Analytics
// ---------------------------------------------------------------------------

export const mockScorecard = {
  period: 7,
  activity: {
    totalJobs: 42,
    running: 2,
    inReview: 4,
    merged: 28,
    prCreated: 3,
    discarded: 2,
    failed: 2,
    cancelled: 1,
  },
  budget: [
    {
      sdk: "copilot",
      totalCostUsd: 18.42,
      premiumRequests: 847,
      jobCount: 26,
      avgCostPerJob: 0.71,
      avgDurationMs: 480000,
    },
    {
      sdk: "claude",
      totalCostUsd: 24.86,
      premiumRequests: 0,
      jobCount: 16,
      avgCostPerJob: 1.55,
      avgDurationMs: 620000,
    },
  ],
  quotaJson: null,
  costTrend: [
    { date: "2026-03-25", cost: 4.2, jobs: 5 },
    { date: "2026-03-26", cost: 6.8, jobs: 7 },
    { date: "2026-03-27", cost: 5.1, jobs: 6 },
    { date: "2026-03-28", cost: 8.4, jobs: 9 },
    { date: "2026-03-29", cost: 7.2, jobs: 6 },
    { date: "2026-03-30", cost: 6.9, jobs: 5 },
    { date: "2026-03-31", cost: 4.6, jobs: 4 },
  ],
};

export const mockModelComparison = {
  period: 7,
  repo: null,
  models: [
    {
      model: "claude-sonnet-4.6",
      sdk: "copilot",
      jobCount: 20,
      avgCost: 0.65,
      avgDurationMs: 440000,
      totalCostUsd: 13.0,
      premiumRequests: 620,
      merged: 16,
      prCreated: 2,
      discarded: 1,
      failed: 1,
      avgVerifyTurns: null,
      verifyJobCount: 0,
      avgDiffLines: 45,
      cacheHitRate: 0.72,
      costPerJob: 0.65,
      costPerMinute: 0.089,
      costPerTurn: 0.018,
      costPerToolCall: 0.005,
    },
    {
      model: "claude-sonnet-4.6",
      sdk: "claude",
      jobCount: 14,
      avgCost: 1.48,
      avgDurationMs: 580000,
      totalCostUsd: 20.72,
      premiumRequests: 0,
      merged: 10,
      prCreated: 1,
      discarded: 1,
      failed: 2,
      avgVerifyTurns: null,
      verifyJobCount: 0,
      avgDiffLines: 68,
      cacheHitRate: 0.65,
      costPerJob: 1.48,
      costPerMinute: 0.153,
      costPerTurn: 0.032,
      costPerToolCall: 0.009,
    },
    {
      model: "claude-3-5-haiku-20250120",
      sdk: "claude",
      jobCount: 8,
      avgCost: 0.52,
      avgDurationMs: 320000,
      totalCostUsd: 4.14,
      premiumRequests: 0,
      merged: 6,
      prCreated: 0,
      discarded: 1,
      failed: 1,
      avgVerifyTurns: null,
      verifyJobCount: 0,
      avgDiffLines: 28,
      cacheHitRate: 0.78,
      costPerJob: 0.52,
      costPerMinute: 0.098,
      costPerTurn: 0.012,
      costPerToolCall: 0.003,
    },
  ],
};

export const mockAnalyticsTools = {
  period: 7,
  tools: [
    { tool: "replace_string_in_file", category: "file_write", calls: 342, failures: 12, failureRate: 0.035, avgDurationMs: 48, p50: 42, p95: 85, p99: 120 },
    { tool: "read_file", category: "file_read", calls: 890, failures: 3, failureRate: 0.003, avgDurationMs: 35, p50: 28, p95: 72, p99: 110 },
    { tool: "run_in_terminal", category: "shell", calls: 215, failures: 28, failureRate: 0.13, avgDurationMs: 3200, p50: 1800, p95: 8500, p99: 15000 },
    { tool: "grep_search", category: "file_search", calls: 410, failures: 1, failureRate: 0.002, avgDurationMs: 120, p50: 95, p95: 280, p99: 450 },
    { tool: "create_file", category: "file_write", calls: 156, failures: 2, failureRate: 0.013, avgDurationMs: 42, p50: 38, p95: 75, p99: 100 },
    { tool: "semantic_search", category: "file_search", calls: 178, failures: 5, failureRate: 0.028, avgDurationMs: 850, p50: 620, p95: 2100, p99: 3800 },
  ],
};

export const mockAnalyticsRepos = {
  period: 7,
  repos: [
    { repo: REPO_ISSUE_TRACKER, jobCount: 24, totalCostUsd: 22.4, avgCostPerJob: 0.93, avgDurationMs: 520000, toolCalls: 1280, premiumRequests: 450 },
    { repo: REPO_SUPPORT_DASH, jobCount: 18, totalCostUsd: 20.88, avgCostPerJob: 1.16, avgDurationMs: 580000, toolCalls: 910, premiumRequests: 397 },
  ],
};

export const mockCostDrivers = {
  period: 7,
  dimension: "overall",
  summary: [],
};

export const mockObservations = {
  observations: [],
};

// Realistic telemetry data for the running job — matches the shape of
// GET /api/jobs/{id}/telemetry from the real backend.
export const runningJobTelemetry = {
  available: true,
  jobId: "customer-email-search",
  sdk: "copilot",
  model: "claude-sonnet-4.6",
  mainModel: "claude-sonnet-4.6",
  durationMs: 264000,
  inputTokens: 4_218_400,
  outputTokens: 28_350,
  totalTokens: 8_012_750,
  cacheReadTokens: 3_766_000,
  cacheWriteTokens: 0,
  totalCost: 0.65,
  contextWindowSize: 200_000,
  currentContextTokens: 67_420,
  contextUtilization: 0.337,
  compactions: 0,
  tokensCompacted: 0,
  toolCallCount: 47,
  totalToolDurationMs: 18_230,
  toolCalls: [
    { name: "report_intent", durationMs: 0.5, success: true, offsetSec: 2.1 },
    { name: "bash", durationMs: 812, success: true, offsetSec: 3.0 },
    { name: "bash", durationMs: 745, success: true, offsetSec: 4.2 },
    { name: "grep", durationMs: 34, success: true, offsetSec: 8.5 },
    { name: "glob", durationMs: 41, success: true, offsetSec: 8.6 },
    { name: "grep", durationMs: 68, success: false, offsetSec: 9.1 },
    { name: "view", durationMs: 12, success: true, offsetSec: 12.4 },
    { name: "view", durationMs: 65, success: true, offsetSec: 13.0 },
    { name: "view", durationMs: 71, success: true, offsetSec: 13.1 },
    { name: "grep", durationMs: 25, success: true, offsetSec: 16.8 },
    { name: "view", durationMs: 330, success: true, offsetSec: 19.2 },
    { name: "bash", durationMs: 798, success: true, offsetSec: 22.0 },
    { name: "edit", durationMs: 290, success: true, offsetSec: 28.5 },
    { name: "edit", durationMs: 185, success: true, offsetSec: 31.2 },
    { name: "bash", durationMs: 515, success: true, offsetSec: 34.0 },
    { name: "bash", durationMs: 590, success: true, offsetSec: 38.7 },
    { name: "view", durationMs: 228, success: true, offsetSec: 42.1 },
    { name: "edit", durationMs: 310, success: true, offsetSec: 45.3 },
    { name: "bash", durationMs: 1045, success: true, offsetSec: 48.8 },
    { name: "bash", durationMs: 2340, success: false, offsetSec: 52.1 },
    { name: "edit", durationMs: 175, success: true, offsetSec: 56.4 },
    { name: "bash", durationMs: 3120, success: true, offsetSec: 60.0 },
    { name: "view", durationMs: 18, success: true, offsetSec: 68.2 },
    { name: "view", durationMs: 92, success: true, offsetSec: 70.5 },
    { name: "edit", durationMs: 220, success: true, offsetSec: 74.3 },
    { name: "bash", durationMs: 4510, success: true, offsetSec: 78.0 },
  ],
  llmCallCount: 38,
  totalLlmDurationMs: 186_400,
  llmCalls: [
    { model: "claude-sonnet-4.6", inputTokens: 61_350, outputTokens: 182, cacheReadTokens: 7_430, cacheWriteTokens: 0, cost: 0.02, durationMs: 4450, isSubagent: false, offsetSec: 0.5, callCount: 1 },
    { model: "claude-sonnet-4.6", inputTokens: 66_720, outputTokens: 210, cacheReadTokens: 7_430, cacheWriteTokens: 0, cost: 0.02, durationMs: 5260, isSubagent: false, offsetSec: 5.0, callCount: 1 },
    { model: "claude-sonnet-4.6", inputTokens: 20_710, outputTokens: 287, cacheReadTokens: 6_800, cacheWriteTokens: 0, cost: 0.01, durationMs: 6670, isSubagent: false, offsetSec: 10.0, callCount: 1 },
    { model: "claude-sonnet-4.6", inputTokens: 74_450, outputTokens: 186, cacheReadTokens: 22_670, cacheWriteTokens: 0, cost: 0.02, durationMs: 4650, isSubagent: false, offsetSec: 15.2, callCount: 1 },
    { model: "claude-sonnet-4.6", inputTokens: 67_230, outputTokens: 119, cacheReadTokens: 66_520, cacheWriteTokens: 0, cost: 0.01, durationMs: 3930, isSubagent: false, offsetSec: 20.5, callCount: 1 },
    { model: "claude-haiku-4.5", inputTokens: 5_445, outputTokens: 689, cacheReadTokens: 0, cacheWriteTokens: 0, cost: 0.003, durationMs: 4310, isSubagent: true, offsetSec: 25.0, callCount: 1 },
    { model: "claude-haiku-4.5", inputTokens: 10_200, outputTokens: 331, cacheReadTokens: 0, cacheWriteTokens: 0, cost: 0.003, durationMs: 3220, isSubagent: true, offsetSec: 30.0, callCount: 1 },
    { model: "claude-sonnet-4.6", inputTokens: 67_370, outputTokens: 198, cacheReadTokens: 67_230, cacheWriteTokens: 0, cost: 0.02, durationMs: 4570, isSubagent: false, offsetSec: 35.0, callCount: 1 },
    { model: "claude-sonnet-4.6", inputTokens: 76_040, outputTokens: 599, cacheReadTokens: 74_300, cacheWriteTokens: 0, cost: 0.02, durationMs: 16_180, isSubagent: false, offsetSec: 40.0, callCount: 1 },
    { model: "claude-sonnet-4.6", inputTokens: 78_200, outputTokens: 420, cacheReadTokens: 76_040, cacheWriteTokens: 0, cost: 0.02, durationMs: 5800, isSubagent: false, offsetSec: 58.0, callCount: 1 },
    { model: "claude-sonnet-4.6", inputTokens: 80_100, outputTokens: 350, cacheReadTokens: 78_200, cacheWriteTokens: 0, cost: 0.02, durationMs: 4200, isSubagent: false, offsetSec: 65.0, callCount: 1 },
    { model: "claude-sonnet-4.6", inputTokens: 82_400, outputTokens: 280, cacheReadTokens: 80_100, cacheWriteTokens: 0, cost: 0.02, durationMs: 3900, isSubagent: false, offsetSec: 72.0, callCount: 1 },
  ],
  approvalCount: 0,
  totalApprovalWaitMs: 0,
  agentMessages: 38,
  operatorMessages: 2,
  premiumRequests: 38,
  quotaSnapshots: {
    "github-models": {
      usedRequests: 847,
      entitlementRequests: 999999,
      remainingPercentage: 99.9,
      overage: 0,
      overageAllowed: false,
      isUnlimited: true,
      usageAllowedWithExhaustedQuota: true,
      resetDate: "2026-04-15T00:00:00Z",
    },
  },
  costDrivers: {
    activity: [
      { dimension: "activity", bucket: "command_execution", costUsd: 0.22, inputTokens: 1_580_000, outputTokens: 8_400, callCount: 18 },
      { dimension: "activity", bucket: "code_reading", costUsd: 0.18, inputTokens: 1_210_000, outputTokens: 6_200, callCount: 14 },
      { dimension: "activity", bucket: "code_changes", costUsd: 0.14, inputTokens: 890_000, outputTokens: 7_800, callCount: 8 },
      { dimension: "activity", bucket: "search_discovery", costUsd: 0.06, inputTokens: 340_000, outputTokens: 2_100, callCount: 5 },
      { dimension: "activity", bucket: "verification", costUsd: 0.04, inputTokens: 150_000, outputTokens: 3_200, callCount: 3 },
      { dimension: "activity", bucket: "user_communication", costUsd: 0.01, inputTokens: 48_400, outputTokens: 650, callCount: 1 },
    ],
  },
  turnEconomics: {
    totalTurns: 12,
    peakTurnCostUsd: 0.08,
    avgTurnCostUsd: 0.054,
    costFirstHalfUsd: 0.38,
    costSecondHalfUsd: 0.27,
    turnCurve: [
      { dimension: "turn", bucket: "1", costUsd: 0.04, inputTokens: 128_000, outputTokens: 860, callCount: 2 },
      { dimension: "turn", bucket: "2", costUsd: 0.05, inputTokens: 154_000, outputTokens: 1_200, callCount: 3 },
      { dimension: "turn", bucket: "3", costUsd: 0.06, inputTokens: 168_000, outputTokens: 1_800, callCount: 4 },
      { dimension: "turn", bucket: "4", costUsd: 0.08, inputTokens: 190_000, outputTokens: 2_400, callCount: 5 },
      { dimension: "turn", bucket: "5", costUsd: 0.07, inputTokens: 178_000, outputTokens: 2_100, callCount: 4 },
      { dimension: "turn", bucket: "6", costUsd: 0.06, inputTokens: 172_000, outputTokens: 1_600, callCount: 3 },
      { dimension: "turn", bucket: "7", costUsd: 0.08, inputTokens: 195_000, outputTokens: 2_800, callCount: 5 },
      { dimension: "turn", bucket: "8", costUsd: 0.06, inputTokens: 170_000, outputTokens: 1_900, callCount: 3 },
      { dimension: "turn", bucket: "9", costUsd: 0.05, inputTokens: 155_000, outputTokens: 1_400, callCount: 3 },
      { dimension: "turn", bucket: "10", costUsd: 0.04, inputTokens: 142_000, outputTokens: 1_100, callCount: 2 },
      { dimension: "turn", bucket: "11", costUsd: 0.05, inputTokens: 158_000, outputTokens: 1_600, callCount: 3 },
      { dimension: "turn", bucket: "12", costUsd: 0.06, inputTokens: 165_000, outputTokens: 2_000, callCount: 3 },
    ],
  },
  fileAccess: {
    stats: {
      totalAccesses: 42,
      uniqueFiles: 8,
      totalReads: 38,
      totalWrites: 4,
      rereadCount: 12,
    },
    topFiles: [
      { filePath: "src/routes/tickets.py", accessCount: 8, readCount: 6, writeCount: 2 },
      { filePath: "src/services/ticket_service.py", accessCount: 6, readCount: 5, writeCount: 1 },
      { filePath: "tests/test_tickets.py", accessCount: 5, readCount: 4, writeCount: 1 },
      { filePath: "src/models/ticket.py", accessCount: 4, readCount: 4, writeCount: 0 },
      { filePath: "src/routes/__init__.py", accessCount: 3, readCount: 3, writeCount: 0 },
    ],
  },
};

export const mockOverview = {
  period: 7,
  totalJobs: 42,
  succeeded: 28,
  review: 4,
  completed: 3,
  failed: 2,
  cancelled: 1,
  running: 2,
  totalCostUsd: 43.28,
  totalTokens: 2840000,
  avgDurationMs: 540000,
  totalPremiumRequests: 847,
  totalToolCalls: 2191,
  totalToolFailures: 51,
  totalAgentErrors: 3,
  totalToolErrors: 48,
  toolSuccessRate: 0.977,
  cacheHitRate: 0.71,
  costTrend: mockScorecard.costTrend,
};
